### ISSUE TITLE
AbortErrors when using Cow in FireFox

### ISSUE THREAD

**Issue by Rupke75** [Geodan/cow#142] opened 2014-09-10 14:26 UTC
AbortError on line 564 in cow.js
at
var request = store.put(record);

This occurs when starting cow with the icm-ui client in FireFox

**Comment by tomvantilburg** [comment] 2015-03-10 13:45
This is reproducable by refreshing firefox within some seconds of opening the app.
Since this situation is not likely to happen often and the effects of it appear to be minimal I close this.

**Closed by tomvantilburg** 2015-03-10 13:45 UTC
Labels: bug, core, Prio 2
